# Generated by Django 5.2 on 2025-04-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_role',
            field=models.CharField(blank=True, default='member', max_length=20, null=True),
        ),
    ]
